// This file is generated by Slice Machine. Update with care!

import Features from './Features';
import Footer from './Footer';
import Hero from './Hero';
import ImageAndText from './ImageAndText';
import TestSlice from './TestSlice';

export {
	Features,
	Footer,
	Hero,
	ImageAndText,
	TestSlice,
};

export const components = {
	features: Features,
	footer: Footer,
	hero: Hero,
	image_and_text: ImageAndText,
	test_slice: TestSlice,
};
